version: '3'
services:
  db:
    image: 'postgres:11'
    container_name: 'cataloged_postgres'
    ports:
      - '54320:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata:
